services:
  
  frontend: 
    build:
      context: ./client-app
      args:
        COMMIT_SHA: ${COMMIT_SHA}
    image: asset-frontend:${COMMIT_SHA}
    container_name: angular_client
    # ports:
    #   - "4200:80"
    expose:
      - "80"
    # volumes:
    #   - ./client-app:/app
    #   - angular_node_modules:/app/node_modules
    networks:
      - app-network
  
  laravel:
    build:
      context: ./laravel
    container_name: laravel_api
    # ports:
    #   - "8000:8000"
    expose:
      - "9000"
    volumes:
      - ./laravel:/var/www/html
      - laravel_vendor:/var/www/html/vendor
    networks:
      - app-network

  realtime-server:
    build:
      context: ./realtime-server
    container_name: realtime_server
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./realtime-server:/app
      - realtime_node_modules:/app/node_modules
    networks:
      - app-network 
    
  nginx:
    build:
      context: ./nginx
    container_name: gateway
    ports:
      - "80:80"
    depends_on:
      - frontend
      - laravel
      - realtime-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  angular_node_modules:
  realtime_node_modules:
  laravel_vendor:

