# FROM php:8.4
FROM php:8.4-fpm
# System dependencies

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    git curl unzip zip \
    libpng-dev libonig-dev \
    # git \
    # curl \
    # unzip \
    # zip \
    # libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libwebp-dev \
    libzip-dev \
    pkg-config

RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp

RUN docker-php-ext-install zip pdo pdo_mysql gd sockets

RUN pecl install redis \
    && docker-php-ext-enable redis

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer



# COPY composer.json composer.lock ./

# RUN composer install --no-interaction --prefer-dist --no-scripts

COPY . .

RUN composer install --no-interaction --prefer-dist


# EXPOSE 8000

# CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
RUN chown -R www-data:www-data storage bootstrap/cache
# CMD ["php", "artisan", "serve"]
EXPOSE 9000
CMD ["php-fpm"]