# FROM php:8.4
FROM php:8.4-fpm
# System dependencies

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    git curl unzip zip \
    libpng-dev libonig-dev \
    git \
    curl

RUN docker-php-ext-install pdo pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer



# COPY composer.json composer.lock ./

# RUN composer install --no-interaction --prefer-dist --no-scripts

COPY . .

RUN composer install --no-interaction --prefer-dist


# EXPOSE 8000

# CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
RUN chown -R www-data:www-data storage bootstrap/cache
# CMD ["php", "artisan", "serve"]
EXPOSE 9000
CMD ["php-fpm"]