# ---- Build Stage ----
FROM node:20 AS build

WORKDIR /app

# Install dependencies first (better caching)
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .
RUN find src -type f | sort
RUN npm run build 

# Expose Angular dev server port
# EXPOSE 4200

# IMPORTANT: bind to 0.0.0.0 so Docker can access it
# CMD ["npm", "start"]

# ---- Runtime Stage ----
FROM nginx:alpine
COPY --from=build /app/dist/client-app/browser/ /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]