FROM node:20

WORKDIR /app

# Install dependencies first (better caching)
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose Angular dev server port
EXPOSE 4200

# IMPORTANT: bind to 0.0.0.0 so Docker can access it
CMD ["npm", "start"]