name: CI

on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: assetmanagement_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
          DB_CONNECTION: mysql
          DB_HOST: 192.168.56.102
          DB_PORT: 3306
          DB_DATABASE: assetmanagement_test
          DB_USERNAME: ams_user
          DB_PASSWORD: HIKbUxZg19rAazkZ

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_mysql, zip, sockets
          coverage: none

      - name: Install Composer dependencies
        working-directory: laravel
        run: composer install --no-interaction --prefer-dist

      - name: Create Laravel environment
        working-directory: laravel
        run: |
          cp .env.example .env
          php artisan key:generate

      # - name: Check MySQL service
      #   run: nc -zv 192.168.56.102 3306

      # - name: Check database connection
      #   working-directory: laravel
      #   run: php artisan db:show
        
      - name: Run database migrations
        working-directory: laravel
        run: php artisan migrate --force

      - name: Run PHPUnit tests
        working-directory: laravel
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 192.168.56.102
          DB_PORT: 3306
          DB_DATABASE: assetmanagement_test
          DB_USERNAME: ams_user
          DB_PASSWORD: HIKbUxZg19rAazkZ
        run: php artisan test

      

      